name: toopdbq
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.2.0+5

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.22.0
  firebase_storage: ^10.3.7
  firebase_database: ^9.1.3

  sqflite:
  path:
  hooks_riverpod: ^1.0.4
  firebase_messaging: ^13.0.0
  flutter_hooks: ^0.18.5+1
  firebase_auth: ^3.7.0
  sign_in_with_apple: ^3.3.0
  google_sign_in: ^5.4.1
  image_cropper: ^3.0.0
  image_picker: ^0.8.5+3
  connectivity_plus: ^2.3.7
  scroll_to_index: ^3.0.1
  flutter_launcher_icons: ^0.10.0
  flutter_app_badger: ^1.5.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  flutter_datetime_picker: ^1.5.1
  numberpicker: ^2.1.1
  cloud_firestore: ^3.5.1
  shared_preferences: ^2.0.15
  flutter_picker: ^2.0.5
  audioplayers: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - audio/
    - images/
flutter_icons:
  android: true
  ios: true
  image_path: "images/icon_app.png"