// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANyy0ZJ-nDIjL1nBx5Fl2-QBWCJHCs2IU',
    appId: '1:666088321479:web:d50a5b9eec8ef3c1fc69e2',
    messagingSenderId: '666088321479',
    projectId: 'toopdbq',
    authDomain: 'toopdbq.firebaseapp.com',
    databaseURL: 'https://toopdbq-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'toopdbq.appspot.com',
    measurementId: 'G-PNMRS2CYEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHvetyPAIt3oFO8ezh65QbGPKwCkVUo6Y',
    appId: '1:666088321479:android:480fb9680a45de5dfc69e2',
    messagingSenderId: '666088321479',
    projectId: 'toopdbq',
    databaseURL: 'https://toopdbq-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'toopdbq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqNtmtK9FKljMyXfl0lmKYiwXwZye2INM',
    appId: '1:666088321479:ios:a5ef59e075b43feafc69e2',
    messagingSenderId: '666088321479',
    projectId: 'toopdbq',
    databaseURL: 'https://toopdbq-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'toopdbq.appspot.com',
    androidClientId: '666088321479-8cm7mo870tf660g7fuomr7sgfekr94dh.apps.googleusercontent.com',
    iosClientId: '666088321479-25ujrl2ilcchpifgcpfj2uaoh0047c25.apps.googleusercontent.com',
    iosBundleId: 'com.ubh.toopdbq',
  );
}
